name: Build Debug

on:
  [ push, pull_request ]

env:
  SOLUTION_NAME: FFXIV_ReadyCheck
  ZIP_PATH: ReadyCheck\bin\Debug\

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Debug

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: DebugFolder
          path: ${{ env.ZIP_PATH }}
          if-no-files-found: error
